In [1]:
import numpy as np

1. Tạo mảng:

Tạo mảng một chiều (1D) chứa 10 số nguyên ngẫu nhiên từ 0 đến 100. <br>
Tạo mảng hai chiều (2D) chứa 5 hàng và 3 cột, với các giá trị được khởi tạo bằng 0.<br>
Tạo mảng ba chiều (3D) chứa 2 khối 3x3x3, với các giá trị được khởi tạo bằng 1.

In [9]:
arr_1D = np.random.randint(0,100, (11))
arr_2D = np.zeros([5,3])
arr_3D = np.ones((2,3,3,3))

print(arr_1D)
print(arr_2D)
print(arr_3D)

[20 78  5 48 79 45 51 16 88 24 66]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]]


2. Truy cập phần tử:

Truy cập và in ra phần tử đầu tiên, phần tử cuối cùng của mảng 1D.<br>
Truy cập và in ra phần tử tại vị trí (2, 1) của mảng 2D.<br>
Truy cập và thay đổi giá trị của phần tử tại vị trí (1, 1, 1) của mảng 3D.<br>
Chuyển đổi mảng 2D sang mảng 1D và ngược lại.