#Bài tập 1: Thao tác với ma trận  
**Lý thuyết**:  
NumPy cung cấp các công cụ mạnh mẽ để thao tác ma trận, bao gồm tính toán các định thức, tìm nghịch đảo và tính toán các giá trị riêng và vectơ riêng.
  
**Đề bài**:  
Tạo ma trận 5x5 ngẫu nhiên và thực hiện các thao tác sau:  
* Tính định thức (determinant) của ma trận.  
* Tìm nghịch đảo (transpose) của ma trận.  
* Tính các giá trị riêng (eigent value) và vectơ riêng (eigent vector) của ma trận.   
(Phần này sẽ liên quan tới đại số tuyến tính, mọi người có thể tự tìm hiểu để hiểu chi tiết về các khái niệm trên)

<details>
  <summary>Hint</summary>

```python
import numpy as np

# Generate a random 5x5 matrix
matrix = np.random.rand(5, 5)

# Compute determinant
det = np.linalg.det(matrix)

# Find inverse
inverse = np.linalg.inv(matrix)

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

```
</details>

In [5]:
import numpy as np

In [7]:
# Your code here

matrix = np.random.randint(1, 100, size = (5,5))
print('Ma trận: ', matrix)

# Tính định thức của ma trận
determinant = np.linalg.det(matrix)
print("Định thức của ma trận là:", determinant)

# Tìm nghịch đảo (transpose) của ma trận.
transpose = matrix.T
print('nghịch đảo (transpose) của ma trận', transpose)

# Tính các giá trị riêng và vectơ riêng
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Các giá trị riêng của ma trận là:", eigenvalues)
print("Các vectơ riêng tương ứng:")
print(eigenvectors)

Ma trận:  [[93 97 99 30 66]
 [16 65 13  4 45]
 [15 79 67  3  4]
 [ 7  9  8 69  8]
 [74 40 36 46 92]]
Định thức của ma trận là: 392903669.9999997
nghịch đảo (transpose) của ma trận [[93 16 15  7 74]
 [97 65 79  9 40]
 [99 13 67  8 36]
 [30  4  3 69 46]
 [66 45  4  8 92]]
Các giá trị riêng của ma trận là: [219.71829415 +0.j           7.10304797 +0.j
  47.31112587+40.76025583j  47.31112587-40.76025583j
  64.55640613 +0.j        ]
Các vectơ riêng tương ứng:
[[ 0.71560139+0.j         -0.62393507+0.j          0.21215   -0.40192269j
   0.21215   +0.40192269j -0.464352  +0.j        ]
 [ 0.26888696+0.j         -0.31352323+0.j         -0.15624916+0.38004145j
  -0.15624916-0.38004145j  0.05714746+0.j        ]
 [ 0.2268232 +0.j          0.5390486 +0.j          0.57391983+0.j
   0.57391983-0.j         -0.2867947 +0.j        ]
 [ 0.09298022+0.j         -0.01436788+0.j         -0.01596453-0.00350581j
  -0.01596453+0.00350581j  0.81751571+0.j        ]
 [ 0.59625528+0.j          0.47077423+0.j         

# Bài tập 2: Optimization
**Lý thuyết:**  
Gradient descent là một thuật toán tối ưu hóa được sử dụng để cực tiểu hóa hàm bằng cách di chuyển lặp đi lặp lại theo hướng dốc xuống.

**Đề bài:**  
Triển khai gradient descent sử dụng NumPy để tối ưu hàm số sau:
 $$ f(x) = x^2 + 5 \sin(x) $$
<details>
  <summary>Hint</summary>

```python
import numpy as np

def gradient_descent(x, learning_rate, iterations):
    for _ in range(iterations):
        gradient = 2*x + 5*np.cos(x)  # Đạo hàm riêng theo x
        x = x - learning_rate * gradient # Cập nhật tham số
    return x

# Khởi tạo các hyperparameters
x_initial = 5  # Input đầu vào
learning_rate = 0.1 # Tốc độ học
iterations = 100 # Số lần lặp

# Run gradient descent
minima = gradient_descent(x_initial, learning_rate, iterations)
```

</details>

In [9]:
# Your code here

import numpy as np

def gradient_descent(x, learning_rate, iterations):
    for _ in range(iterations):
        gradient = 2*x + 5*np.cos(x)  # Đạo hàm riêng theo x
        x = x - learning_rate * gradient # Cập nhật tham số
    return x

# Khởi tạo các hyperparameters
x_initial = 5  # Input đầu vào
learning_rate = 0.1 # Tốc độ học
iterations = 100 # Số lần lặp

# Run gradient descent
minima = gradient_descent(x_initial, learning_rate, iterations)
minima

-1.110510503581112

# Bài tập 3: Phân tích thống kê  
**Lý thuyết**:  
NumPy cung cấp các chức năng để phân tích thống kê, bao gồm tính toán giá trị trung bình (mean), trung vị (median), độ lệch chuẩn (standard deviation) và mối tương quan (correlation).  

**Đề Bài**:  
Thực hiện phân tích thống kê trên tập dữ liệu bai3.csv bằng NumPy:  
* Tính giá trị trung bình, trung vị và độ lệch chuẩn của tập dữ liệu.
* Tính toán ma trận tương quan giữa các biến khác nhau.
* Xác định các ngoại lệ trong tập dữ liệu bằng cách sử dụng điểm z.

<details>
  <summary>Hint</summary>

```python
  # Load dataset
  data = np.loadtxt('dataset.csv', delimiter=',')

  # Calculate mean, median, and standard deviation
  mean = np.mean(data, axis=0)
  median = np.median(data, axis=0)
  std_dev = np.std(data, axis=0)

  # Compute correlation matrix
  correlation_matrix = np.corrcoef(data, rowvar=False)

  # Identify outliers using z-scores
  z_scores = np.abs((data - mean) / std_dev)
  outliers = np.where(z_scores > 3)
```
</details>

In [12]:
# Your code here

data = np.loadtxt('bai3.csv', delimiter=',', skiprows=1)

data_mean = np.mean(data, axis=0)

data_median = np.median(data, axis=0)

data_std = np. std(data, axis=0)

data_correlation = np.corrcoef(data, rowvar=False)

z_scores = np.abs((data - data_mean) / data_std)
outliers = np.where(z_scores > 3)

print('Giá trị trung vị: ', data_median)
print('Giá trị trung bình: ', data_mean)  
print('Độ lệch chuẩn: ', data_std) 
print('Độ tương quan giữa các biến: ', data_correlation)
print('Các ngoại lệ trong tập dữ liệu: ', outliers)

Giá trị trung vị:  [3.1 3.8 6.7 2.6 7.1]
Giá trị trung bình:  [3.42 3.82 6.48 2.72 7.32]
Độ lệch chuẩn:  [1.56639714 0.59799666 1.25443214 0.75736385 1.32272446]
Độ tương quan giữa các biến:  [[1.         0.47784764 0.89183434 0.61500461 0.94868903]
 [0.47784764 1.         0.81104187 0.97063145 0.71505798]
 [0.89183434 0.81104187 1.         0.88457426 0.98139657]
 [0.61500461 0.97063145 0.88457426 1.         0.79617986]
 [0.94868903 0.71505798 0.98139657 0.79617986 1.        ]]
Các ngoại lệ trong tập dữ liệu:  (array([], dtype=int64), array([], dtype=int64))


# Bài 4: Thao tác với tensor
Đề cho một tensor đại diện cho một hình ảnh thang độ xám. Thực hiện các thao tác sau:

1. Reshape: Reshape tensor thành một hình dạng khác trong khi vẫn đảm bảo tổng số phần tử không đổi.
2. Transpose: Transpose tensor dọc theo các trục được chỉ định.
3. Slice: Trích xuất một tập hợp con của tensor bằng cách cắt dọc theo các kích thước được chỉ định.
4. Concatenate: Concatenate nhiều tensor dọc theo các trục được chỉ định.
5. Các phép toán theo phần tử: Thực hiện các phép toán theo phần tử như cộng, trừ, nhân và chia với các giá trị vô hướng hoặc các tensor khác.
6. Hoạt động rút gọn: Thực hiện các hoạt động rút gọn như tính tổng, trung bình, tối thiểu và tối đa dọc theo các trục được chỉ định.
7. Indexing: Truy cập các phần tử riêng lẻ hoặc các tensor phụ bằng cách sử dụng các chỉ số nguyên hoặc boolean mark.

<details>
  <summary>Hint</summary>

  ```python
    # 1. Reshape the tensor
    reshaped_tensor = image_tensor.reshape(1, 9)

    # 2. Transpose the tensor
    transposed_tensor = image_tensor.T

    # 3. Slice the tensor
    sliced_tensor = image_tensor[:2, :2]

    # 4. Concatenate tensors
    concatenated_tensor = np.concatenate((image_tensor, image_tensor), axis=0)

    # 5. Element-wise operations
    added_tensor = image_tensor + 0.1
    multiplied_tensor = image_tensor * 2

    # 6. Reduction operations
    sum_tensor = np.sum(image_tensor)
    mean_tensor = np.mean(image_tensor, axis=0)
    max_tensor = np.max(image_tensor, axis=1)

    # 7. Indexing
    element = image_tensor[1, 2]
  ```
</details>

In [14]:
image_tensor = np.array([
    [0.1, 0.2, 0.3],
    [0.4, 0.5, 0.6],
    [0.7, 0.8, 0.9]
])

In [35]:
# your code here

reshaped_tensor = image_tensor.reshape(1, 9)
print('Reshape tensor thành một hình dạng khác', reshaped_tensor)

transpose_tensor = np.transpose(reshaped_tensor)
print('Transpose: \n', transpose_tensor)

slice_tensor = image_tensor[:2, 1:3]
print('Trích xuất một tập hợp con của tensor \n', slice_tensor)

image_tensor2 = np.array([[0.5, 0.7, 0.6]])
concatenate_tensor = np.concatenate((image_tensor, image_tensor2), axis=0)
print('Concatenate nhiều tensor \n', concatenate_tensor)

total_tensor = image_tensor + 2
print('Cộng với 1 giá trị vô hướng: \n', total_tensor)

minus_tensor = image_tensor - image_tensor2
print('Trừ 2 vector: \n', minus_tensor)

mul_tensor = np.multiply(image_tensor, 3)
print('Tích với 1 giá trị vô hướng: \n', mul_tensor)

div_tensor = np.divide(image_tensor,image_tensor2)
print('Chia 2 vector: \n', div_tensor)

sum_axis0 = np.sum(image_tensor, axis = 0)
print('Tổng hàng: \n', sum_axis0)

mean_axis1 = np.mean(image_tensor, axis = 1)
print('Trung bình cột: \n', mean_axis1)

max_axis0 = np.max(image_tensor, axis = 0)
print('Lớn nhất hàng: \n', max_axis0)

min_axis1 = np.max(image_tensor, axis = 1)
print('Nhỏ nhất cột: \n', min_axis1)

element = image_tensor[0:2, 1:3]
print('Truy cập phần tử với các hàng từ 0 đến 1 và cột từ 1 đến 2: \n', element)

mask = image_tensor > 0.5
sub_tensor = image_tensor[mask]
print("Tensor phụ bằng boolean mask: \n", sub_tensor)

Reshape tensor thành một hình dạng khác [[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]]
Transpose: 
 [[0.1]
 [0.2]
 [0.3]
 [0.4]
 [0.5]
 [0.6]
 [0.7]
 [0.8]
 [0.9]]
Trích xuất một tập hợp con của tensor 
 [[0.2 0.3]
 [0.5 0.6]]
Concatenate nhiều tensor 
 [[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]
 [0.5 0.7 0.6]]
Cộng với 1 giá trị vô hướng: 
 [[2.1 2.2 2.3]
 [2.4 2.5 2.6]
 [2.7 2.8 2.9]]
Trừ 2 vector: 
 [[-0.4 -0.5 -0.3]
 [-0.1 -0.2  0. ]
 [ 0.2  0.1  0.3]]
Tích với 1 giá trị vô hướng: 
 [[0.3 0.6 0.9]
 [1.2 1.5 1.8]
 [2.1 2.4 2.7]]
Chia 2 vector: 
 [[0.2        0.28571429 0.5       ]
 [0.8        0.71428571 1.        ]
 [1.4        1.14285714 1.5       ]]
Tổng hàng: 
 [1.2 1.5 1.8]
Trung bình cột: 
 [0.2 0.5 0.8]
Lớn nhất hàng: 
 [0.7 0.8 0.9]
Nhỏ nhất cột: 
 [0.3 0.6 0.9]
Truy cập phần tử với các hàng từ 0 đến 1 và cột từ 1 đến 2: 
 [[0.2 0.3]
 [0.5 0.6]]
Tensor phụ bằng boolean mask: 
 [0.6 0.7 0.8 0.9]
